apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-dep
  namespace: eri
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
       app: web
    spec:
      containers:
      - name: first-dep
        image: ermirzela/epic:latest
---
apiVersion: v1
kind: Service
metadata:
  name: first-entrypoint
  namespace: eri
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001


